# Install script for directory: /home/zhuwei/Documents/PX4/MyPX4

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/msg/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/drivers/boards/sitl/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/drivers/device/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/drivers/gps/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/drivers/pwm_out_sim/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/platforms/common/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/platforms/posix/drivers/accelsim/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/platforms/posix/drivers/adcsim/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/platforms/posix/drivers/airspeedsim/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/platforms/posix/drivers/barosim/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/platforms/posix/drivers/gpssim/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/platforms/posix/drivers/gyrosim/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/platforms/posix/drivers/ledsim/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/platforms/posix/drivers/rgbledsim/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/platforms/posix/drivers/tonealrmsim/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/platforms/posix/px4_layer/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/platforms/posix/work_queue/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/systemcmds/esc_calib/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/systemcmds/mixer/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/systemcmds/param/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/systemcmds/perf/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/systemcmds/reboot/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/systemcmds/sd_bench/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/systemcmds/topic_listener/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/systemcmds/ver/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/systemcmds/top/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/systemcmds/motor_ramp/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/attitude_estimator_ekf/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/attitude_estimator_q/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/commander/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/dataman/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/ekf2/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/ekf_att_pos_estimator/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/fw_att_control/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/fw_pos_control_l1/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/land_detector/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/logger/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/mavlink/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/mc_att_control/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/mc_att_control_multiplatform/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/mc_pos_control/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/mc_pos_control_multiplatform/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/navigator/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/param/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/position_estimator_inav/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/local_position_estimator/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/replay/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/sdlog2/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/sensors/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/simulator/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/systemlib/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/systemlib/mixer/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/uORB/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/vtol_att_control/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/controllib/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/conversion/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/DriverFramework/framework/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/ecl/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/external_lgpl/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/geo/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/geo_lookup/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/launchdetection/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/mathlib/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/mathlib/math/filter/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/rc/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/runway_takeoff/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/tailsitter_recovery/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/terrain_estimation/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/examples/px4_simple_app/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/drivers/sf0x/sf0x_tests/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/lib/rc/rc_tests/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/commander/commander_tests/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/controllib_test/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/unit_test/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/modules/uORB/uORB_tests/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/systemcmds/tests/cmake_install.cmake")
  include("/home/zhuwei/Documents/PX4/MyPX4/qt_proj/src/firmware/posix/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/home/zhuwei/Documents/PX4/MyPX4/qt_proj/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
